// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/heartbeat.porto

package com.github.proto.hearbaet;

public final class PacketProto {
  private PacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.protobuf.hearbaet.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
     */
    int getPacketTypeValue();
    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
     */
    com.github.proto.hearbaet.PacketProto.Packet.PacketType getPacketType();

    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code com.github.protobuf.hearbaet.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.protobuf.hearbaet.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      packetType_ = 0;
      data_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Packet();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              packetType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.proto.hearbaet.PacketProto.internal_static_com_github_protobuf_hearbaet_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.proto.hearbaet.PacketProto.internal_static_com_github_protobuf_hearbaet_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.proto.hearbaet.PacketProto.Packet.class, com.github.proto.hearbaet.PacketProto.Packet.Builder.class);
    }

    /**
     * <pre>
     * 包的类型
     * </pre>
     *
     * Protobuf enum {@code com.github.protobuf.hearbaet.Packet.PacketType}
     */
    public enum PacketType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 心跳包
       * </pre>
       *
       * <code>HEARTBEAT = 0;</code>
       */
      HEARTBEAT(0),
      /**
       * <pre>
       * 非心跳包
       * </pre>
       *
       * <code>DATA = 1;</code>
       */
      DATA(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 心跳包
       * </pre>
       *
       * <code>HEARTBEAT = 0;</code>
       */
      public static final int HEARTBEAT_VALUE = 0;
      /**
       * <pre>
       * 非心跳包
       * </pre>
       *
       * <code>DATA = 1;</code>
       */
      public static final int DATA_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PacketType valueOf(int value) {
        return forNumber(value);
      }

      public static PacketType forNumber(int value) {
        switch (value) {
          case 0: return HEARTBEAT;
          case 1: return DATA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PacketType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
              public PacketType findValueByNumber(int number) {
                return PacketType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.proto.hearbaet.PacketProto.Packet.getDescriptor().getEnumTypes().get(0);
      }

      private static final PacketType[] VALUES = values();

      public static PacketType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PacketType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.github.protobuf.hearbaet.Packet.PacketType)
    }

    public static final int PACKETTYPE_FIELD_NUMBER = 1;
    private int packetType_;
    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
     */
    public int getPacketTypeValue() {
      return packetType_;
    }
    /**
     * <pre>
     * 包类型
     * </pre>
     *
     * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
     */
    public com.github.proto.hearbaet.PacketProto.Packet.PacketType getPacketType() {
      @SuppressWarnings("deprecation")
      com.github.proto.hearbaet.PacketProto.Packet.PacketType result = com.github.proto.hearbaet.PacketProto.Packet.PacketType.valueOf(packetType_);
      return result == null ? com.github.proto.hearbaet.PacketProto.Packet.PacketType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 数据部分（可选，心跳包不包含数据部分）
     * </pre>
     *
     * <code>string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetType_ != com.github.proto.hearbaet.PacketProto.Packet.PacketType.HEARTBEAT.getNumber()) {
        output.writeEnum(1, packetType_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetType_ != com.github.proto.hearbaet.PacketProto.Packet.PacketType.HEARTBEAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packetType_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.proto.hearbaet.PacketProto.Packet)) {
        return super.equals(obj);
      }
      com.github.proto.hearbaet.PacketProto.Packet other = (com.github.proto.hearbaet.PacketProto.Packet) obj;

      if (packetType_ != other.packetType_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKETTYPE_FIELD_NUMBER;
      hash = (53 * hash) + packetType_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.proto.hearbaet.PacketProto.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.proto.hearbaet.PacketProto.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.protobuf.hearbaet.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.protobuf.hearbaet.Packet)
        com.github.proto.hearbaet.PacketProto.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.proto.hearbaet.PacketProto.internal_static_com_github_protobuf_hearbaet_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.proto.hearbaet.PacketProto.internal_static_com_github_protobuf_hearbaet_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.proto.hearbaet.PacketProto.Packet.class, com.github.proto.hearbaet.PacketProto.Packet.Builder.class);
      }

      // Construct using com.github.proto.hearbaet.PacketProto.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packetType_ = 0;

        data_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.proto.hearbaet.PacketProto.internal_static_com_github_protobuf_hearbaet_Packet_descriptor;
      }

      @java.lang.Override
      public com.github.proto.hearbaet.PacketProto.Packet getDefaultInstanceForType() {
        return com.github.proto.hearbaet.PacketProto.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.proto.hearbaet.PacketProto.Packet build() {
        com.github.proto.hearbaet.PacketProto.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.proto.hearbaet.PacketProto.Packet buildPartial() {
        com.github.proto.hearbaet.PacketProto.Packet result = new com.github.proto.hearbaet.PacketProto.Packet(this);
        result.packetType_ = packetType_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.proto.hearbaet.PacketProto.Packet) {
          return mergeFrom((com.github.proto.hearbaet.PacketProto.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.proto.hearbaet.PacketProto.Packet other) {
        if (other == com.github.proto.hearbaet.PacketProto.Packet.getDefaultInstance()) return this;
        if (other.packetType_ != 0) {
          setPacketTypeValue(other.getPacketTypeValue());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.proto.hearbaet.PacketProto.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.proto.hearbaet.PacketProto.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int packetType_ = 0;
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
       */
      public int getPacketTypeValue() {
        return packetType_;
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
       */
      public Builder setPacketTypeValue(int value) {
        packetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
       */
      public com.github.proto.hearbaet.PacketProto.Packet.PacketType getPacketType() {
        @SuppressWarnings("deprecation")
        com.github.proto.hearbaet.PacketProto.Packet.PacketType result = com.github.proto.hearbaet.PacketProto.Packet.PacketType.valueOf(packetType_);
        return result == null ? com.github.proto.hearbaet.PacketProto.Packet.PacketType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
       */
      public Builder setPacketType(com.github.proto.hearbaet.PacketProto.Packet.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        packetType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 包类型
       * </pre>
       *
       * <code>.com.github.protobuf.hearbaet.Packet.PacketType packetType = 1;</code>
       */
      public Builder clearPacketType() {
        
        packetType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据部分（可选，心跳包不包含数据部分）
       * </pre>
       *
       * <code>string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.protobuf.hearbaet.Packet)
    }

    // @@protoc_insertion_point(class_scope:com.github.protobuf.hearbaet.Packet)
    private static final com.github.proto.hearbaet.PacketProto.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.proto.hearbaet.PacketProto.Packet();
    }

    public static com.github.proto.hearbaet.PacketProto.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.proto.hearbaet.PacketProto.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_protobuf_hearbaet_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_protobuf_hearbaet_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/protobuf/heartbeat.porto\022\034com.gith" +
      "ub.protobuf.hearbaet\"\202\001\n\006Packet\022C\n\npacke" +
      "tType\030\001 \001(\0162/.com.github.protobuf.hearba" +
      "et.Packet.PacketType\022\014\n\004data\030\002 \001(\t\"%\n\nPa" +
      "cketType\022\r\n\tHEARTBEAT\020\000\022\010\n\004DATA\020\001B*\n\031com" +
      ".github.proto.hearbaetB\013PacketProtoH\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_protobuf_hearbaet_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_protobuf_hearbaet_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_protobuf_hearbaet_Packet_descriptor,
        new java.lang.String[] { "PacketType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
