// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GrpcStudend.porto

package com.github.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
