// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/GrpcStudend.porto

package com.github.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.github.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.github.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.github.proto.StudentResponse studentResponse = 1;</code>
   */
  com.github.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.github.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.github.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.github.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.github.proto.StudentResponse studentResponse = 1;</code>
   */
  com.github.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
